# Generated by Django 5.1 on 2024-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[("fruits", "Fruits"), ("vegetables", "Vegetables")],
                        max_length=50,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Pink Lady", "Pink Lady"),
                            ("chiquita", "Chiquita"),
                            ("Gala", "Gala"),
                            ("Fyffes", "Fyffes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=4)),
                ("stock", models.IntegerField()),
            ],
        ),
    ]
