# Generated by Django 5.1 on 2024-08-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
    ]
